# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0-solc-0.7
  - cowprotocol/contracts@1.3.1
  - balancer/balancer-v2-monorepo@weighted-deployment

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.7.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0-solc-0.7"
      - "@cow-protocol=cowprotocol/contracts@1.3.1/src"
      - "@balancer=balancer/balancer-v2-monorepo@weighted-deployment/contracts"

reports:
  exclude_contracts:
    - SafeMath