name: Tests

on:
  push:
    branches:
    - main
    - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Run tests
      run: forge test -vv --fork-url "https://mainnet.infura.io/v3/b7821200399e4be2b4e5dbdf06fbe85b" --etherscan-api-key "MW5CQA6QK5YMJXP2WP3RA36HM5A7RA1IHA" --ffi

